on:
  push:
    branches:
      - master
  workflow_dispatch:

name: Build Site

jobs:
  build:
    name: Build & Deploy Pages
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Git User
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com" 
          git config --global user.name "GitHub Actions"
 
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
          
      - run: npm install
      
      - run: npm run deploy -- -m "Deploy React app to GitHub Pages"
        
